name: petto_api
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  dart_frog: ^1.0.0
  dart_frog_auth: ^1.1.0
  data:
    path: packages/data
  postgres: ^3.4.1
  repositories:
    path: packages/repositories
  services:
    path: packages/services

dev_dependencies:
  migrant: ^0.3.0
  migrant_db_postgresql: ^0.3.0
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
